version: "3"
services:
  webapp:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 5000:5000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower