version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.1.0

  workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - deploy-to-heroku/docker-build-release:
          app-name: simple-web-xue